apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-nfs-test
  namespace: test
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /nfs
    server: 192.168.29.155
  claimRef:
    name: pvc-postgre
    namespace: test
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgre
  namespace: test
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi