# SERVICE_FE
apiVersion: v1
kind: Service
metadata:
  name: test-nfs-service
  namespace: test
  # Labels
  labels:
    app: test-nfs
spec:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 15672
        targetPort: 15672
      - name: port-traffic
        protocol: TCP
        port: 5672
        targetPort: 5672
    selector:
      app: test-nfs
    externalIPs:
      - 192.168.29.155