# SERVICE_FE
apiVersion: v1
kind: Service
metadata:
  name: test-kibana-service
  namespace: test
  # Labels
  labels:
    app: test-svc-kibana
spec:
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 5601
        targetPort: 5601
    selector:
      app: test-kibana
    externalIPs:
      - 192.168.29.155