# DEPLOY_FE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-nginx-proxy-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: test-nginx-proxy-manager
    spec:
      containers:
      - image: jc21/nginx-proxy-manager:latest
        name: nginx-proxy-manager
        imagePullPolicy: Always